name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Carthage modules
        uses: actions/cache@v1
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
      - name: Bundle Install
        run: |
          bundle install
      - name: Use Swift 5.2.2
        uses: YOCKOW/Action-setup-swift@master
        with:
          swift-version: '5.2.2'
      - name: Carthage update
        if: steps.carthage-cache.outputs.cache-hit != 'true'
        run: |
          brew install automake autoconf libtool gettext libevent openssl
          ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
          carthage bootstrap --platform iOS --cache-builds --toolchain org.swift.520202003241a

  test:
    needs: [build]
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Carthage modules
        uses: actions/cache@v1
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
      - name: Use Swift 5.2.2
        uses: YOCKOW/Action-setup-swift@master
        with:
          swift-version: '5.2.2'
      - name: Run Verge Wallet Service
        run: |
          cd ./Docker
          docker-compose up -d
          cd ..
        env:
            TRUSTED_XVG_MAINNET_PEER: verged
            TRUSTED_XVG_MAINNET_PEER_PORT: 21102
            BITCORE_CONFIG_PATH: /usr/src/app/bitcore.config.json
            BN_MONGODB_HOST: database
            BN_MONGODB_NAME: bitcore
            BN_MONGODB_PORT: 27017
            BWS_NODE_URL: http://bitcore-node:3000
            BWS_MONGODB_URL: mongodb://database:27017/vws
      - name: Run tests
        run: |
          fastlane test
