name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Cache Carthage modules
        uses: actions/cache@preview
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Bundle Install
        run: |
          bundle install
      - name: Use Swift 5.2
        uses: YOCKOW/Action-setup-swift@master
        with:
          swift-version: '5.2'
      - name: Carthage update
        run: |
          carthage update --platform iOS --cache-builds --toolchain org.swift.520202003241a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: [build]
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Cache Carthage modules
        uses: actions/cache@preview
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Run tests
        run: |
          fastlane test
