name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Carthage modules
        uses: actions/cache@v1
        id: carthage-cache
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
      - name: Bundle Install
        run: |
          bundle install
      - name: Use Swift 5.2
        uses: YOCKOW/Action-setup-swift@master
        with:
          swift-version: '5.2'
      - name: Carthage update
        if: steps.carthage-cache.outputs.cache-hit != 'true'
        run: |
          brew install automake autoconf libtool gettext libevent openssl
          ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
          carthage bootstrap --platform iOS --cache-builds --toolchain org.swift.520202003241a

  test:
    needs: [build]
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Carthage modules
        uses: actions/cache@v1
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
      - name: Use Swift 5.2
        uses: YOCKOW/Action-setup-swift@master
        with:
          swift-version: '5.2'
      - name: Run tests
        run: |
          fastlane test
