name: CI

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Select XCode 11.4
        run: |
          xcode-select --switch /Applications/Xcode_11.4_beta.app/Contents/Developer
      - name: Cache Carthage modules
        uses: actions/cache@preview
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Bundle Install
        run: |
          bundle install
      - name: Carthage update
        run: |
          chmod u+x install.sh && ./install.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Select XCode 11.4
        run: |
          xcode-select --switch /Applications/Xcode_11.4_beta.app/Contents/Developer
      - name: Cache Carthage modules
        uses: actions/cache@preview
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: |
            ${{ runner.os }}-carthage-
      - name: Run tests
        run: |
          fastlane test
